// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMfdPW3O3FE612bVLr8b8-j5qk1otICqU',
    appId: '1:693658099749:web:4442e94c7df23c2d025fcc',
    messagingSenderId: '693658099749',
    projectId: 'algorand-344721',
    authDomain: 'algorand-344721.firebaseapp.com',
    storageBucket: 'algorand-344721.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdR69wVMccFHDCAIYozhz91ZvV6xnufEU',
    appId: '1:693658099749:android:3b17cd7d16252366025fcc',
    messagingSenderId: '693658099749',
    projectId: 'algorand-344721',
    storageBucket: 'algorand-344721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPpXWe7ABAATl7OO3soFkBivUi1oAQ1lY',
    appId: '1:693658099749:ios:80cd08d3b7e5a54d025fcc',
    messagingSenderId: '693658099749',
    projectId: 'algorand-344721',
    storageBucket: 'algorand-344721.appspot.com',
    iosClientId:
        '693658099749-brotmk4jlo7vr06q3nv8h84rc70k06ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.commerce',
  );
}
